require('pry-byebug')
require_relative("models/tickets")
require_relative("models/screenings")
require_relative("models/customers")
require_relative("models/films")

Ticket.delete_all()
Screening.delete_all()
Customer.delete_all()
Film.delete_all()

customer1 = Customer.new({ 'name' => "David Mulligan", 'fund' => 50})
customer1.save()
customer2 = Customer.new({ 'name' => "Kirsty Love", 'fund' => 20})
customer2.save()
customer3 = Customer.new({ 'name' => "Simon Mulligan", 'fund' => 10})
customer3.save()
customer4 = Customer.new({ 'name' => "Stevie McCaul", 'fund' => 15})
customer4.save()
customer5 = Customer.new({ 'name' => "Juliet Langton", 'fund' => 27})
customer5.save()
customer6 = Customer.new({ 'name' => "Natasha Wright", 'fund' => 32})
customer6.save()
customer7 = Customer.new({ 'name' => "Elske Tolkamp", 'fund' => 12})
customer7.save()
customer8 = Customer.new({ 'name' => "George Takei", 'fund' => 50})
customer8.save()
customer9 = Customer.new({ 'name' => "Morgan Freeman", 'fund' => 60})
customer9.save()
customer10 = Customer.new({ 'name' => "John Barrowman", 'fund' => 45})
customer10.save()

film1 = Film.new({ 'name' => "Baby Driver", 'price' => 8})
film1.save()
film2 = Film.new({ 'name' => "Thor Ragnarok", 'price' => 10})
film2.save()
film3 = Film.new({ 'name' => "Star Wars: The Last Jedi", 'price' => 14})
film3.save()
film4 = Film.new({ 'name' => "Atomic Blonde", 'price' => 9})
film4.save()
film5 = Film.new({ 'name' => "Spiderman Homecoming", 'price' => 7})
film5.save()

screening1 = Screening.new({'film_times' => '16:00', 'availability' => 10})
screening1.save()
screening2 = Screening.new({'film_times' => '18:00', 'availability' => 5})
screening2.save()
screening3 = Screening.new({'film_times' => '12:00', 'availability' => 7})
screening3.save()
screening4 = Screening.new({'film_times' => '21:00', 'availability' => 9})
screening4.save()
screening5 = Screening.new({'film_times' => '10:00', 'availability' => 12})
screening5.save()
screening6 = Screening.new({'film_times' => '9:00', 'availability' => 10})
screening6.save()
screening7 = Screening.new({'film_times' => '12:30', 'availability' => 5})
screening7.save()
screening8 = Screening.new({'film_times' => '20:00', 'availability' => 7})
screening8.save()
screening9 = Screening.new({'film_times' => '11:00', 'availability' => 9})
screening9.save()
screening10 = Screening.new({'film_times' => '17:00', 'availability' => 12})
screening10.save()


ticket1 = Ticket.new({ 'customer_id' => customer1.id, 'film_id' => film2.id, 'screening_id' => screening2.id})
ticket1.save()
ticket2 = Ticket.new({ 'customer_id' => customer2.id, 'film_id' => film1.id, 'screening_id' => screening1.id})
ticket2.save()
ticket3 = Ticket.new({ 'customer_id' => customer3.id, 'film_id' => film3.id, 'screening_id' => screening8.id})
ticket3.save()
ticket4 = Ticket.new({ 'customer_id' => customer3.id, 'film_id' => film4.id, 'screening_id' => screening4.id})
ticket4.save()
ticket5 = Ticket.new({ 'customer_id' => customer3.id, 'film_id' => film1.id, 'screening_id' => screening1.id})
ticket5.save()
ticket6 = Ticket.new({ 'customer_id' => customer7.id, 'film_id' => film5.id, 'screening_id' => screening10.id})
ticket6.save()
ticket7 = Ticket.new({ 'customer_id' => customer7.id, 'film_id' => film2.id, 'screening_id' => screening7.id})
ticket7.save()
ticket8 = Ticket.new({ 'customer_id' => customer8.id, 'film_id' => film3.id, 'screening_id' => screening8.id})
ticket8.save()
ticket9 = Ticket.new({ 'customer_id' => customer8.id, 'film_id' => film2.id, 'screening_id' => screening7.id})
ticket9.save()
ticket10 = Ticket.new({ 'customer_id' => customer8.id, 'film_id' => film5.id, 'screening_id' => screening5.id})
ticket10.save()
ticket11 = Ticket.new({ 'customer_id' => customer4.id, 'film_id' => film1.id, 'screening_id' => screening1.id})
ticket11.save()
ticket12 = Ticket.new({ 'customer_id' => customer4.id, 'film_id' => film4.id, 'screening_id' => screening4.id})
ticket12.save()
ticket13 = Ticket.new({ 'customer_id' => customer5.id, 'film_id' => film2.id, 'screening_id' => screening2.id})
ticket13.save()
ticket14 = Ticket.new({ 'customer_id' => customer5.id, 'film_id' => film1.id, 'screening_id' => screening6.id})
ticket14.save()
ticket15 = Ticket.new({ 'customer_id' => customer5.id, 'film_id' => film5.id, 'screening_id' => screening5.id})
ticket15.save()
ticket16 = Ticket.new({ 'customer_id' => customer6.id, 'film_id' => film2.id, 'screening_id' => screening2.id})
ticket16.save()
ticket17 = Ticket.new({ 'customer_id' => customer6.id, 'film_id' => film5.id, 'screening_id' => screening10.id})
ticket17.save()
ticket18 = Ticket.new({ 'customer_id' => customer9.id, 'film_id' => film1.id, 'screening_id' => screening6.id})
ticket18.save()
ticket19 = Ticket.new({ 'customer_id' => customer9.id, 'film_id' => film3.id, 'screening_id' => screening3.id})
ticket19.save()
ticket20 = Ticket.new({ 'customer_id' => customer10.id, 'film_id' => film2.id, 'screening_id' => screening7.id})
ticket20.save()
ticket21 = Ticket.new({ 'customer_id' => customer10.id, 'film_id' => film4.id, 'screening_id' => screening9.id})
ticket21.save()
ticket22 = Ticket.new({ 'customer_id' => customer10.id, 'film_id' => film5.id, 'screening_id' => screening10.id})
ticket22.save()


# customer3.name = "Sarah Mulligan"
# customer3.update
#
# film3.name = "Atomic Blonde"
# film3.update
#
# customer3.delete

binding.pry
nil
